---
- name: Start services.
  shell: systemctl start pcsd.service

- name: Enable pcsd.service.
  shell: systemctl enable pcsd.service

- name: Check the status of the pcsd service.
  shell: systemctl status pcsd.service

- name: Setup cluster auth.
  shell: pcs cluster auth "{{ node1 }}"."{{ fqdn }}" "{{ node2 }}"."{{ fqdn }}"

- name: Start the Cluster.
  status: pcs cluster setup --start --name gpfscluster "{{ node1 }}"."{{ fqdn }}"  "{{ node2 }}"."{{ fqdn }}"

- name: Check cluster status.
  shell: pcs cluster enable --all

- name: Check status of enable command.
  register: cluster_enable
  shell: "pcs cluster enable --all"

- name: Print the status of "pcs cluster able --all"
  debug:
    msg: "Is the cluster enabled {{ cluster_enable }}"
    
- name: Print the status of the cluster
  register: cluster_status
  shell: "pcs cluster status"

- name: Print the output of "pcs cluster status"
  debug:
    msg: "The cluster status is {{ cluster_status }}"

- name: Check pcs status.
  register: pcs_status
  shell: "pcs status"

- name: print pcs status.
  debug:
    msg: " The pcs status is {{ pcs_status }}"