---
- name: Starting pcsd services 
  shell:
    "systemctl start pcsd.service"

- name: Enable pcsd services
  shell:
    "systemctl enable pcsd.service"

- name: check the status of the pcsd services
  shell: 
    "systemctl status pcsd.service"
    
