---
- name: Create resource
  register: createresource
  ansible.builtin.shell:
    - pcs resource create uzmgwyw-dlm ocf:pacemaker:controld op monitor interval=30s on-fail=fence clone interleave=true ordered=true
   
  debug:
    mesg: createresource

- name: Enable cluster
  register: enablecluster
  ansible.builtin.shell:
    - /sbin/lvmconf --enable-cluster 

- name: create Heartbeat
  ansible.builtin.shell:
    - pcs resource create uzmgwyw-clvmd ocf:heartbeat:clvm op monitor interval=30s on-fail=fence clone interleave=true ordered=true

  debug: 
    msg: "The status is {{ enablecluster }}"

# - name: create constraints
#   ansible.builtin.shell: |
#     - pcs constraint order start uzmgwyw-dlm-clone then uzmgwyw-clvmd-clone
#     - pcs constraint colocation add uzmgwyw-clvmd-clone with uzmgwyw-dlm-clone

- name: set property
  ansible.builtin.shell: 
    - pcs property set no-quorum-policy=freeze

- name: stop lvm
  register: statuslvmetad
  ansible.builtin.shell: systemctl '{{ item }}'
  loop:
    - stop lvm2-lvmetad
    - disable lvm2-lvmetad
    - status lvm2-lvmetad

  debug:
    mesg: "The status is {{ statuslvmetad }}"

- name: Setting up Cluster auth
  command:
    - pcs cluster auth UZMGWYW1.zm.sbicdirectory.com UZMGWYW2.zm.sbicdirectory.com

- name: Start the cluster.
  command:
    - pcs cluster setup --start --name gpfscluster UZMGWYW1.zm.sbicdirectory.com  UZMGWYW2.zm.sbicdirectory.com

- name: Enable the cluster.
  command: 
     - pcs cluster enable --all

- name: checking cluster status
  register: cluster_status
  command: 
    - pcs cluster status

- name: displaying cluster status.
  debug:
    msg: "The cluster status is {{ cluster_status }}"

- name: Checking pcs status.
  register: pcs_status
  command:
    - pcs status

- name: Displaying pcs status.
  debug:
    msg: "pcs status is {{ pcs_status }}"

- name: Configure fencing.
  command:
    - 'fence_vmware_rest -a {{ vsphere_host }}.{{ fqdn }} -l fenceuser@vsphere.local -p P@ssw0rd -z --ssl-insecure -o list'
    - 'fence_vmware_rest -a {{ vsphere_host }}.{{ fqdn }} -l fenceuser@vsphere.local -p ZambiaMQ@2021 -z --ssl-insecure -o list'
    - 'pcs stonith create {{ fence_name }} fence_vmware_rest pcmk_host_map="{{ node1 }}.{{ fqdn }}:"{{ vsphere_host1: }}";{{ node2 }}.{{ fqdn }}:"{{ vsphere_host2 }}" \
       ipaddr="afrzamdrvc01v.zm.sbicdirectory.com" login="fenceuser@vsphere.local" passwd="ZambiaMQ@2021" ssl_insecure=1  pcmk_monitor_timeout=60s'

- name : Get show Stonith.
  register: pcs_stonith_show
  command:
    - 'pcs stonith show pbwgwywfence'

- name: Show stonith show results.
  debug:
    msg: "The output of pcs status show is {{ pcs_stonith_show }}"

- name: Get stonith show full
  register: stonith_show_full
  command: 
    - 'pcs stonith show --full'

- name: Show get stonith full results.
  debug:
    msg: "Stonith show all is {{ stonith_show_full }}"

- name: Get stonith show results.
  register: stonith_show
  
  command: 
    - 'pcs stonith show'

- name: Show stonith show results.
  debug:
    msg: stonith_show