---

- name: Install packages
  yum:
    name: "{{ item }}"
    state: latest
    # register: yuminstall
  loop:
    - bc
    - ksh
    # - fuser
    - psmisc
    - sysstat
    - gzip
    - bzip2
    - net-tools
    - gpm-libs
    - ncompress
    - pam.i686
    - xxd
    - unix2dos
    - dos2unix
    - strace
    - telnet
    - glibc.i686
    - mksh
# - name: get the output from the install.
#   debug:
#     msg: "{{ yuminstall.stdout }}"
