- hosts: all
  remote_user: root
  become: yes 
  become_method: sudoers
  sereial: 10
  vars_file:
    - vars.yml

  roles:
    - repos
    - packages
    - groups
    - users
    - sudoers
    - makedirectories
    - limits