---
- hosts: all
  remote_user: dries 
  become: yes
  become_method: sudo
  serial: 10

  roles:
    - repos
    #- packages
    - groups
    - users
    - sudoers
    - makedirectories
    - limits
