---

- name: check the status of the cluster.
  ansible.builtin.shell:
  register: pcs_status
  cmd:
    - pcs status

  debug:
    msg: "pcs status is {{ pcs_status.stdout }}"

- name: Check the pcs config
  ansible.builtin.shell:
  register: pcs_config
  cmd:
    - pcs config

  debug:
    msg: "PCS config is {{ pcs_config.stdout }}"
