---

- name: Update security limits.
  blockinfile:
    path: /etc/security/limits.limits.conf
    insertafter: EOF
    block: |
      mqm             soft    nofile          10240
      mqm             hard    nofile          10240
      mqm             soft    nproc           10240
      mqm             hard    nproc           10240
      *               hard    nofile          10240
      *               hard    stack           10240
      *               soft    nofile          10240
