---
- name: Checking that group esbcom exists.
  ansible.builtin.group:
    name: esbcom
    state: present

- name: Ensure group mqbrkrs exists.
  ansible.builtin.group:
    name: mqbrkrs
    state: present
    gid: 19998

