---
- name: Ensure group "esbcom" exists.
  group:
    name: esbcom
    state: present

- name: Ensure group "mqbrkrs" exists.
  group:
    name: mqbrkrs
    state: present
    gid: 19998

  tags: create_groups