---
- name: "Create partitions on devices"    
  block:   
    - name: install parted
      package:
        name: parted
        state: present 
        
    - name: "Read device information /dev/sdb"
      parted: 
        device: "/dev/sdb"
        unit: MiB
      register: device_info
    
    - name: "Add new partition /dev/sdb1"
      parted: 
        device: "/dev/sdb"
        number: "1"
        part_type: primary
        flags: [ lvm ]
        state: present
        part_end: "100%"
        part_start: "{{ device_info.partitions[0].end + 1}}MiB" 
        
    - name: "Add device to exising volume group {{ ClusterDatavg }}."
      lvg:
        vg: "{{ ClusterDatavg }}"
        pvs: "/dev/sdb1"
      
    - name: lvcreate
      lvol:
            vg: ClusterDatavg
            lv: "{{ items }}"
            size: 30G

    - name: create file system
      filesystem:
            fstype: gfs
            dev: /dev/mapper/ClusterDatavg-" {{ items }}"
      with_items:
         - ubwgwyw1datalv
         - ubwgwyw2datalv
         - ubwgwyw1loglv
         - ubwgwyw2loglv
         - ubwfte1datalv
         - ubwfte1loglv

      tags: create_logical_volumes
    
    # - name: mount logical volume
    #   mount:
    #         name: /disk
    #         src: /dev/vgdata/lvdisk
    #         fstype: 
    #         state: mounted  
