---
- name: Update lvm config
  ansible.builtin.replace:
     path: /etc/lvm/lvm.conf
     regexp: '^locking_type'
     replace: 'locking_type = 3'
  tags:
    - lvmconfig

- name: Create physical volume
  community.general.lvg:
  vg: ClusterDatavg
  pvs: /dev/sdb 


- name: Create a Logical volume uzmgwyw1datalv.
  community.general.lvol:
    vg: ClusterDatavg
    lv: uzmgwyw1datalv
    size: 30G

- name: Create a Logical volume uzmgwyw2datalv.
  community.general.lvol:
    vg: ClusterDatavg
    lv: uzmgwyw2datalv
    size: 30G

- name: Create a Logical volume uzmgwyw1loglv.
  community.general.lvol:
    vg: ClusterDatavg
    lv: uzmgwyw1loglv
    size: 30G

- name: Create a Logical volume uzmgwyw2loglv.
  community.general.lvol:
    vg: ClusterDatavg
    lv: uzmgwyw2loglv
    size: 30G

- name: Create a Logical volume uzmfte1datalv.
  community.general.lvol:
    vg: ClusterDatavg
    lv: uzmfte1datalv
    size: 30G

- name: Create a Logical volume uzmfte1loglv.
  community.general.lvol:
    vg: ClusterDatavg
    lv: uzmfte1loglv
    size: 30G

- name: Formatting the created logical volumes.
  ansible.builtin.shell: '{{ item }}'
  loop:
    - mkfs.gfs2 -j2 -p lock_dlm -t gpfscluster:uzmgwyw1datalv /dev/mapper/ClusterDatavg-uzmgwyw1datalv
    - mkfs.gfs2 -j2 -p lock_dlm -t gpfscluster:uzmgwyw2datalv /dev/mapper/ClusterDatavg-uzmgwyw2datalv
    - mkfs.gfs2 -j2 -p lock_dlm -t gpfscluster:uzmgwyw1loglv /dev/mapper/ClusterDatavg-uzmgwyw1loglv
    - mkfs.gfs2 -j2 -p lock_dlm -t gpfscluster:uzmgwyw2loglv /dev/mapper/ClusterDatavg-uzmgwyw2loglv
    - mkfs.gfs2 -j2 -p lock_dlm -t gpfscluster:uzmfte1datalv /dev/mapper/ClusterDatavg-uzmfte1datalv
    - mkfs.gfs2 -j2 -p lock_dlm -t gpfscluster:uzmfte1loglv /dev/mapper/ClusterDatavg-uzmfte1loglv