---
- name: Update lvm config
  ansible.builtin.replace:
     path: /etc/lvm/lvm.conf
     regexp: '^locking_type'
     replace: 'locking_type = 3'
  tags:
    - lvmconfig

- name: Create physical volume
  pv: action=create disks=/dev/sdb --options="--physicalextentsize 128K"
