---
- name: Update lvm config
  ansible.builtin.replace:
     path: /etc/lvm/lvm.conf
     regexp: '^locking_type'
     replace: 'locking_type = 3'
  tags:
    - lvmconfig

- name: Create resource
  register: createresource
  ansible.builtin.shell:
    - pcs resource create uzmgwyw-dlm ocf:pacemaker:controld op monitor interval=30s on-fail=fence clone interleave=true ordered=true
   
  debug:
    mesg: createresource

- name: Enable cluster
  register: enablecluster
  ansible.builtin.shell:
    - /sbin/lvmconf --enable-cluster 

- name: create Heartbeat
  ansible.builtin.shell:
    - pcs resource create uzmgwyw-clvmd ocf:heartbeat:clvm op monitor interval=30s on-fail=fence clone interleave=true ordered=true

  debug: 
    msg: enablecluster