---
- name: Update lvm config
  ansible.builtin.replace:
     path: /etc/lvm/lvm.conf
     regexp: '^locking_type'
     replace: 'locking_type = 3'
  tags:
    - lvmconfig

  vars_files:
    - vars/main.yml

- name: Create physical volume
  community.general.lvg:
  vg: "{{ vgname }}"
  pvs: /dev/sdb 


- name: Create a Logical volume uzmgwyw1datalv.
  community.general.lvol:
    vg: "{{ vgname }}"
    lv: "{{ lvname[0] }}"
    size: 30G
  
- name: Create a Logical volume "{{ lvname[1] }}".
  community.general.lvol:
    vg: "{{ vgname }}"
    lv: "{{ lvname[1] }}"
    size: 30G

- name: Create a Logical volume " {{ lvname[2] }}".
  community.general.lvol:
    vg: "{{ vgname }}"
    lv: "{{ lvname[2] }}"
    size: 30G

- name: Create a Logical volume "{{ lvname[3] }}".
  community.general.lvol:
    vg: "{{ vgname }}"
    lv: "{{ lvname[3] }}"
    size: 30G

- name: Create a Logical volume "{{ lvname[4] }}".
  community.general.lvol:
    vg: "{{ vg_name }}"
    lv: "{{ lvname[4] }}"
    size: 30G

- name: Create a Logical volume "{{ lvname[5] }}".
  community.general.lvol:
    vg: "{{ vg_name }}"
    lv: "{{ lvname[5] }}"
    size: 30G

- name: Formatting the created logical volumes.
  ansible.builtin.shell: '{{ item }}'
  loop:
    - mkfs.gfs2 -j2 -p lock_dlm -t gpfscluster:"{{ lvname[0] }}" /dev/mapper/"{{ vgname }}"-"{{ lvname[0] }}"
    - mkfs.gfs2 -j2 -p lock_dlm -t gpfscluster:"{{ lvname[1] }}" /dev/mapper/"{{ vgname }}"-"{{ lvname[1] }}"
    - mkfs.gfs2 -j2 -p lock_dlm -t gpfscluster:" {{ lvname[2] }}" /dev/mapper/"{{ vgname }}"-" {{ lvname[2] }}"
    - mkfs.gfs2 -j2 -p lock_dlm -t gpfscluster:"{{ lvname[3] }}" /dev/mapper/"{{ vgname }}"-"{{ lvname[3] }}"
    - mkfs.gfs2 -j2 -p lock_dlm -t gpfscluster:"{{ lvname[4] }}" /dev/mapper/"{{ vgname }}"-"{{ lvname[4] }}"
    - mkfs.gfs2 -j2 -p lock_dlm -t gpfscluster:"{{ lvname[5] }}" /dev/mapper/"{{ vgname }}"-"{{ lvname[5] }}"


- name: Create resources.
  ansible.builtin.shell: '{{ item }}'
  loop:
    - pcs resource create uzmgwyw1dataclusterfs Filesystem device="/dev/"{{ vg_name }}"/uzmgwyw1datalv" \
        directory="/gpfsgwy/uzmgwy1/mq/data" fstype="gfs2" "options=noatime" op monitor interval=10s on-fail=fence clone interleave=true
    - pcs resource create uzmgwyw2dataclusterfs Filesystem device="/dev/"{{ vg_name }}"/"{{ lvname[1] }}"" \
        directory="/gpfsgwy/uzmgwy2/mq/data" fstype="gfs2" "options=noatime" op monitor interval=10s on-fail=fence clone interleave=true
    - pcs resource create uzmgwyw1logclusterfs Filesystem device="/dev/"{{ vg_name }}"/" {{ lvname[2] }}"" \
        directory="/gpfsgwy/uzmgwy1/mq/log" fstype="gfs2" "options=noatime" op monitor interval=10s on-fail=fence clone interleave=true
    - pcs resource create uzmgwyw2logclusterfs Filesystem device="/dev/"{{ vg_name }}"/"{{ lvname[3] }}"" \
        directory="/gpfsgwy/uzmgwy2/mq/log" fstype="gfs2" "options=noatime" op monitor interval=10s on-fail=fence clone interleave=true
    - pcs resource create uzmfte1dataclusterfs Filesystem device="/dev/"{{ vg_name }}"/"{{ lvname[4] }}"" \
        directory="/gpfsgwy/uzmfte1/mq/data" fstype="gfs2" "options=noatime" op monitor interval=10s on-fail=fence clone interleave=true
    - pcs resource create uzmfte1logclusterfs Filesystem device="/dev/"{{ vg_name }}"/"{{ lvname[5] }}"" \
        directory="/gpfsgwy/uzmfte1/mq/log" fstype="gfs2" "options=noatime" op monitor interval=10s on-fail=fence clone interleave=true
        


