- pre_tasks:
    - name: update cache
      yum: update_cache=yes cache_valid_time=86400

- name: Installing packages needed.
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      telnet
      libstdc++-devel
      xorg-x11-server-Xorg
      xorg-x11-xauth
      xorg-x11-apps
      xdpyinfo
   
  state: present