
- name: update cache
  yum: 
    update_cache: true

- name: Installing packages needed.
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      telnet
      libstdc++-devel
      xorg-x11-server-Xorg
      xorg-x11-xauth
      xorg-x11-apps
      xdpyinfo
   
  state: latest