---
- hosts: all
  remote_user: dries 
  become: true
  become_method: sudo
  become_user: root
  ignore_errors: yes
  serial: 10
# Add the roles here
  roles:
    - repos
    - packages
    - clusterinstall
    - configureFencing
    - pcs
#Run global tasks here 
