---
- name: Ensure group "esbcom" exists.
  group:
    name: esbcom
    state: present

- name: Ensure group "mqbrkrs" exists.
  group:
    name: mqbrkrs
    state: present
    gid: 19998

- name: Ensure group "iibadm" exists with correct gid
  ansible.builtin.group:
    name: iibadm
    state: present
    gid: 144

- name: Ensure group "fteagent" exists with correct gid
  ansible.builtin.group:
    name: iibadm
    state: present
    gid: 19993

- name: Ensure group "mqm" exists with correct gid
  ansible.builtin.group:
    name: mqm
    state: present
    gid: 206
