---

- name: display limits content.
  shell: cat  /etc/security/limits.conf 
  register: limitsconf

- name: display limits config
  debug:
    msg: "{{ limitsconf.stdout }}"
  
  tags: servicesconf

- name: check if the rsi config exists in xinted
  shell: cat /etc/xinetd.d/rsi
  register: rsiexist

- name: display existance if rsi config.
  debug:
    msg: "{{ rsiexist.stdout }}"

  tags: inetdrsi


