---
- name: Creating the users.
  hosts:  all
  become: true

  tasks:
    - name: Create Users.
      user:
        name: "{{ item }}"
        state: present
        loop:
          - mqm
          - wbrkadm
          - fteagent
          - mqops
          - mqusr
          - wbrkops
          - wbrkusr
          - fteusr
          - iibadm

    - name: Add user mqm to mqbrkrs.
      user:
        name: "{{ item }}"mqm
        groups: mqbrkrs
        append: yes
        loop :
          - mqm
          - esbcom
          - wbrkadm

    - name: Ensure group iibadm exists with the correct gid.
      ansible.buildin.group:
        name: iibadm
        state: present
        gid: 144

    - name: Ensure group esbcom exists.
      ansible.buildin.group: 
      name: esbcom
      state: present
